/*
 ============================================================================
 File Name   : seven_seg.c
 Description : Source file for the 7 segment driver
 Module      : 7 segment
 Author      : Ahmed Ali
 Date        : 26 Sept 2023
 ============================================================================
 */

#include "seven_seg.h"
#include "gpio.h"

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

void SEVENSEGMENT_diplayNumber(uint8 number)
{
#ifndef DECODER_CONFIG
	switch (number)
	{
	case 0:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_LOW);
		break;
	case 1:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_LOW);
		break;
	case 2:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	case 3:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	case 4:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	case 5:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	case 6:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	case 7:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_LOW);
		break;
	case 8:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	case 9:
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID, LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID, LOGIC_HIGH);
		break;
	}
#endif

#ifdef DECODER_CONFIG
	switch (number)
	{
	case 0:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 1:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 2:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 3:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 4:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 5:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 6:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 7:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_LOW);
		break;
	case 8:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_HIGH);
		break;
	case 9:
		GPIO_writePin(DECODER_PORT, DECODER_A_PIN_ID, LOGIC_HIGH);
		GPIO_writePin(DECODER_PORT, DECODER_B_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_C_PIN_ID, LOGIC_LOW);
		GPIO_writePin(DECODER_PORT, DECODER_D_PIN_ID, LOGIC_HIGH);
		break;
	}
#endif
}

void SEVENSEGMENT_init(void)
{
#ifndef DECODER_CONFIG
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_A_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_B_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_C_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_D_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_E_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_F_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_PORT, SEVEN_SEGMENT_G_PIN_ID,
			PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_ENABLE_PORT,
	SEVEN_SEGMENT_ENABLE_PIN_ID, PIN_OUTPUT);
	GPIO_writePin(SEVEN_SEGMENT_ENABLE_PORT, SEVEN_SEGMENT_ENABLE_PIN_ID,
			LOGIC_HIGH);
#endif

#ifdef DECODER_CONFIG
	GPIO_setupPinDirection(DECODER_PORT, DECODER_A_PIN_ID, PIN_OUTPUT);
	GPIO_setupPinDirection(DECODER_PORT, DECODER_B_PIN_ID, PIN_OUTPUT);
	GPIO_setupPinDirection(DECODER_PORT, DECODER_C_PIN_ID, PIN_OUTPUT);
	GPIO_setupPinDirection(DECODER_PORT, DECODER_D_PIN_ID, PIN_OUTPUT);
#endif
}
